name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: ['10', '12', '14', '15']
        
    name: node ${{ matrix.node-versions }} test

    steps:

      - name: Checks out
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-versions }}
          check-latest: true

      - name: Install dependencies
        run: npm install --no-progress

      - name: test with coverage
        run: npm run testWithCoverage
